export const BASE_URL
= 'https://mate-academy.github.io/phone-catalogue-static';

export const GIT_HUB_H2ASH
= 'https://h2ash.github.io';

export const SWITCH_IS_LOADED = 'SWITCH_IS_LOADED';
export const SWITCH_IS_LOADING = 'SWITCH_IS_LOADING';
export const DOWNLOAD_PHONES = 'DOWNLOAD_PHONES';
export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET';
export const PHONES_FROM_STORAGE = 'PHONES_FROM_STORAGE';
export const INCREASE_QUANTITY_IN_BASKET = 'INCREASE_QUANTITY_IN_BASKET';
export const DECREASE_QUANTITY_IN_BASKET = 'DECREASE_QUANTITY_IN_BASKET';
export const DELETE_ITEM_FROM_BASKET = 'DELETE_ITEM_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CALC_QUANTITY_PAGES_AND_THEIR_ARR
  = 'CALC_QUANTITY_PAGES_AND_THEIR_ARR';
